apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-noreadiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-noreadiness
  template:
    metadata:
      labels:
        app: webserver-noreadiness
    spec:
      containers:
      - name: webserver
        image: quay.io/emre_celik/webserver-demo:v1
        command:
          - /bin/sh
          - -c
          - |
            echo "Sleeping before startup"
            sleep 60
            echo "Starting app"
            python server.py
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
